### ISSUE TITLE
Criar diagrama de classes

### ISSUE THREAD

**Issue by ViniSantanaCesar** [next-cesar-school/next20221-t6-parecer-tecnico#15]
Criar diagrama com as classes do projeto

**Comment by DgiooAmoru** [comment]
Diagrama criado
[Diagrama Parecer.pdf](https://github.com/next-cesar-school/next20221-t6-parecer-tecnico/files/8894188/Diagrama.Parecer.pdf)
.

**Comment by DgiooAmoru** [comment]
Task completed.
